name: binah-basic
version: "0.0.0"

dependencies:
- base
- persistent
- persistent-sqlite
- persistent-template
- transformers
- mtl
- aeson
- text
- lio-http-server
- wai
- warp
- bytestring
- mustache
- unordered-containers
- base64-bytestring
- either

executable:
  source-dirs: src
  main: Main
