name: binah
version: "0.0.1"

dependencies:
- base
- persistent
- persistent-sqlite
- persistent-template
- transformers
- mtl
- aeson
- text
- wai
- warp
- bytestring
- mustache
- unordered-containers
- base64-bytestring
- either
- frankie

executable:
  source-dirs: src
  main: Main
