resolver: lts-14.12

packages:
  # - ../persistent/persistent
  # - ../persistent/persistent-template
  # - ../persistent/persistent-sqlite
  # - persistent
  # - persistent-sqlite
  # - persistent-template

extra-deps:
- github: PLSysSec/frankie
  commit: 8894b528847a9f3bdef7ec47e905fc81081c2940
