resolver: lts-13.20

packages:
  # - ../persistent/persistent
  # - ../persistent/persistent-template
  # - ../persistent/persistent-sqlite
  # - persistent
  # - persistent-sqlite
  # - persistent-template
